package com.wxy.bean;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.stock
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    private Long stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sale
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    private Long sale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.onsale
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    private Boolean onsale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.shop_id
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    private Long shopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stock
     *
     * @return the value of product.stock
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    public Long getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stock
     *
     * @param stock the value for product.stock
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    public void setStock(Long stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sale
     *
     * @return the value of product.sale
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    public Long getSale() {
        return sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sale
     *
     * @param sale the value for product.sale
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    public void setSale(Long sale) {
        this.sale = sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.onsale
     *
     * @return the value of product.onsale
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    public Boolean getOnsale() {
        return onsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.onsale
     *
     * @param onsale the value for product.onsale
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    public void setOnsale(Boolean onsale) {
        this.onsale = onsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.shop_id
     *
     * @return the value of product.shop_id
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.shop_id
     *
     * @param shopId the value for product.shop_id
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }
}