package com.wxy.QueueTest.bean;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.title
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.branch
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    private String branch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.descibe
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    private String descibe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.ad
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    private String ad;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.title
     *
     * @return the value of product.title
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.title
     *
     * @param title the value for product.title
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.branch
     *
     * @return the value of product.branch
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.branch
     *
     * @param branch the value for product.branch
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    public void setBranch(String branch) {
        this.branch = branch == null ? null : branch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.descibe
     *
     * @return the value of product.descibe
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    public String getDescibe() {
        return descibe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.descibe
     *
     * @param descibe the value for product.descibe
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    public void setDescibe(String descibe) {
        this.descibe = descibe == null ? null : descibe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.ad
     *
     * @return the value of product.ad
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    public String getAd() {
        return ad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.ad
     *
     * @param ad the value for product.ad
     *
     * @mbggenerated Thu Oct 18 19:16:40 CST 2018
     */
    public void setAd(String ad) {
        this.ad = ad == null ? null : ad.trim();
    }

    @Override
    public String toString() {
        return "Product{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", branch='" + branch + '\'' +
                ", descibe='" + descibe + '\'' +
                ", price=" + price +
                ", ad='" + ad + '\'' +
                '}';
    }
}