package com.wxy.sale.dao;

import java.util.List;

import com.wxy.bean.Mylog;
import com.wxy.bean.MylogExample;
import org.apache.ibatis.annotations.Param;

public interface MylogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylog
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int countByExample(MylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylog
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int deleteByExample(MylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylog
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylog
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int insert(Mylog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylog
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int insertSelective(Mylog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylog
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    List<Mylog> selectByExample(MylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylog
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    Mylog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylog
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Mylog record, @Param("example") MylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylog
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int updateByExample(@Param("record") Mylog record, @Param("example") MylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylog
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int updateByPrimaryKeySelective(Mylog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylog
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int updateByPrimaryKey(Mylog record);
}