package com.wxy.sale.dao;

import java.util.List;

import com.wxy.bean.Product;
import com.wxy.bean.Shop;
import com.wxy.bean.ShopExample;
import org.apache.ibatis.annotations.Param;

public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int countByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int deleteByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int insertSelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    List<Shop> selectByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    Shop selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Shop record, @Param("example") ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int updateByExample(@Param("record") Shop record, @Param("example") ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int updateByPrimaryKeySelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Oct 11 20:16:52 CST 2018
     */
    int updateByPrimaryKey(Shop record);

    void insertBatch(List<Shop> shopList);

    List<Shop> selectShopList(List<Long> shopIds);

    List<Shop> selectShopList2(List<Product> shopIds);
}